version: 2

models:
  - name: stg_salesforce__account
    columns:
      - name: account_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__campaign
    columns:
      - name: campaign_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__case_history
    columns:
      - name: case_history_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__case
    columns:
      - name: case_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__contact
    columns:
      - name: contact_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__opportunity_history
    columns:
      - name: opportunity_history_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__opportunity
    columns:
      - name: opportunity_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__pricebook_entry
    columns:
      - name: pricebook_entry_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__product_2
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__record_type
    columns:
      - name: record_type_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__user_role
    columns:
      - name: user_role_id
        tests:
          - not_null
          - unique
  - name: stg_salesforce__user
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
  - name: dim_user
    columns:
      - name: user_id
        tests:
          - unique
      - name: userroleid
        tests:
          - relationships:
              to: ref('stg_salesforce__user_role')
              field: user_role_id
              config:
                severity: warn
  - name: fct_case
    columns:
      - name: contactid
        tests:
          - relationships:
              to: ref('dim_contact')
              field: contact_id
              config:
                severity: warn
      - name: accountid
        tests:
          - relationships:
              to: ref('dim_account')
              field: account_id
              config:
                severity: warn
      - name: productid
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
              config:
                severity: warn
  - name: fct_opportunity
    columns:
      - name: accountid
        tests:
          - relationships:
              to: ref('dim_account')
              field: account_id
              config:
                severity: warn
      - name: campaignid
        tests:
          - relationships:
              to: ref('dim_campaign')
              field: campaign_id
              config:
                severity: warn